import { VideoItem } from "../types";

export const SAMPLE_VIDEOS: VideoItem[] = [
  {
    id: "vid-001",
    serialId: "#001",
    serialNum: 1,
    filename: "Breaking_Bad_Walter_White_I_Am_The_Danger.mp4",
    fileSize: "45.2 MB",
    duration: "00:54",
    workName: "Breaking Bad",
    identifiedWorkConfidence: "alta",
    year: "2011",
    genre: "Crime / Drama Psicológico",
    subnicho: "Reviravoltas & Conflito Psicológico",
    status: "concluido",
    progress: 100,
    statusMessage: "Pacote completo gerado e validado",
    sceneDescription: "Walter White confronta Skyler na cozinha e profere o lendário monólogo 'Eu sou o perigo', demonstrando a transição total para Heisenberg.",
    frameDataUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=1200&auto=format&fit=crop",
    analysis: {
      identifiedWork: "Breaking Bad (Temporada 4, Ep 6)",
      confidence: "alta",
      genre: "Drama / Crime",
      subnicho: "Reviravoltas & Conflito Psicológico",
      emotion: "Choque & Tensão",
      conflictType: "Homem vs Casamento / Máscara Social vs Monstro Interior",
      viralAngle: "O momento exato em que o protagonista assume publicamente que não é a vítima, mas o predador.",
      whyStopScroll: "A expressão fria e a mudança brusca de tom quebram instantaneamente o ritmo passivo de rolagem.",
      whyRetain: "A construção da frase mantém o espectador preso até a última palavra ('I am the one who knocks').",
      whyComment: "Debate eterno: Walter fez por amor à família ou por pura vaidade psicopata?",
      whyShare: "Uma das falas mais emblemáticas e compartilhadas de toda a história da televisão.",
      viralScore: 97,
      scoreBreakdown: {
        hookStrength: 98,
        curiosityGap: 96,
        visualImpact: 95,
        debatePotential: 99,
        retentionEstimate: 97,
      },
      recommendedThumbnailText: "ELE DESCOBRIU A VERDADE",
    },
    package: {
      selectedHook: "O momento exato em que ele deixou de fingir ser um homem bom.",
      hooks: [
        { id: "h1", category: "choque", text: "O momento exato em que ele deixou de fingir ser um homem bom.", score: 98 },
        { id: "h2", category: "tensão", text: "Ela achava que ele estava em perigo. Ele provou o contrário.", score: 96 },
        { id: "h3", category: "mistério", text: "A fala de 10 segundos que mudou para sempre o rumo da série.", score: 95 },
        { id: "h4", category: "curiosidade", text: "O olhar dele antes de responder revela tudo o que viria a seguir.", score: 93 },
        { id: "h5", category: "reviravolta", text: "Quando você percebe que o vilão da história sempre esteve ali.", score: 97 },
        { id: "h6", category: "conflito", text: "Ele destruiu o casamento com apenas uma única frase.", score: 91 },
        { id: "h7", category: "pergunta", text: "Você defenderia a atitude dele ou ele cruzou todos os limites?", score: 92 },
        { id: "h8", category: "emoção", text: "A atuação visceral que garantiu o Emmy na história da TV.", score: 89 },
        { id: "h9", category: "nostalgia", text: "Quem assistiu a isso na época sentiu o arrepio no primeiro segundo.", score: 94 },
        { id: "h10", category: "debate", text: "Orgulho ou defesa da família? O que realmente motivou essa fala?", score: 95 },
      ],
      selectedTitle: "A frase que transformou Walter White no maior vilão da TV",
      titles: [
        { id: "t1", category: "choque", text: "A frase que transformou Walter White no maior vilão da TV" },
        { id: "t2", category: "suspense", text: "O confronto mais tenso da história de Breaking Bad" },
        { id: "t3", category: "personagem", text: "O nascimento definitivo do Heisenberg na frente de Skyler" },
        { id: "t4", category: "debate", text: "Walter White estava certo ou enlouqueceu de vez aqui?" },
        { id: "t5", category: "curiosidade", text: "O detalhe na direção que quase ninguém percebeu nesta cena" },
        { id: "t6", category: "detalhe", text: "Preste atenção na postura dele antes e depois da frase" },
        { id: "t7", category: "reviravolta", text: "A verdade dolorosa que Skyler não estava pronta para ouvir" },
        { id: "t8", category: "nostalgia", text: "A melhor cena de Breaking Bad segundo os críticos" },
        { id: "t9", category: "emoção", text: "Quando as palavras doeram mais do que qualquer tiro" },
        { id: "t10", category: "mistério", text: "Por que essa é a cena mais perigosa de toda a 4ª temporada?" },
      ],
      selectedCaption: {
        id: "c1",
        style: "Análise Psicológica & Debate",
        text: `\"Você claramente não sabe com quem está falando... EU SOU O PERIGO.\"\n\nEssa cena de Breaking Bad é o divisor de águas absoluto. Walter White não está apenas se defendendo das acusações da esposa; ele está descartando os últimos vestígios do professor humilde para abraçar o império do medo.\n\nBryan Cranston entrega aqui uma das maiores atuações de todos os tempos. Cada respiração e cada sílaba foram calculadas para impor autoridade.\n\nE para você: ele agiu por vaidade pura ou por desespero? Deixe sua opinião nos comentários! 👇🎬`,
        cta: "Ele agiu por vaidade pura ou por desespero? Comente!",
      },
      captions: [
        {
          id: "c1",
          style: "Análise Psicológica & Debate",
          text: `\"Você claramente não sabe com quem está falando... EU SOU O PERIGO.\"\n\nEssa cena de Breaking Bad é o divisor de águas absoluto. Walter White não está apenas se defendendo das acusações da esposa; ele está descartando os últimos vestígios do professor humilde para abraçar o império do medo.\n\nBryan Cranston entrega aqui uma das maiores atuações de todos os tempos. Cada respiração e cada sílaba foram calculadas para impor autoridade.\n\nE para você: ele agiu por vaidade pura ou por desespero? Deixe sua opinião nos comentários! 👇🎬`,
          cta: "Ele agiu por vaidade pura ou por desespero? Comente!",
        },
        {
          id: "c2",
          style: "Curiosidade & Detalhe Oculto",
          text: `Repare na iluminação que corta o rosto dele no momento exato em que ele dá o passo à frente.\n\nA transição de Walter White para Heisenberg não aconteceu com armas ou explosões, mas dentro de uma cozinha comum, durante uma discussão matinal.\n\nVocê teria a mesma coragem ou acha que ele cavou a própria cova? Salve este vídeo para não perder! 🍿`,
          cta: "Você concorda com o que ele disse?",
        },
      ],
      selectedCta: "Você acha que ele tinha razão ou passou de todos os limites?",
      ctas: [
        "Você acha que ele tinha razão ou passou de todos os limites?",
        "Em qual segundo você sentiu o arrepio?",
        "Essa é a cena mais marcante de Breaking Bad? Sim ou Não?",
        "Se você fosse a Skyler, qual seria a sua reação imediata?",
        "Qual nota de 1 a 10 para a atuação de Bryan Cranston aqui?",
      ],
      selectedPinnedComment: {
        id: "pc1",
        category: "debate",
        text: "🔥 DEBATE: Walter virou vilão nessa cena ou ele já era perverso desde o piloto? Quero ver os argumentos da galera aqui embaixo!",
        isMainRecommendation: true,
      },
      pinnedComments: [
        {
          id: "pc1",
          category: "debate",
          text: "🔥 DEBATE: Walter virou vilão nessa cena ou ele já era perverso desde o piloto? Quero ver os argumentos da galera aqui embaixo!",
          isMainRecommendation: true,
        },
        {
          id: "pc2",
          category: "ranking",
          text: "Essa cena entra no seu TOP 1 de falas mais icônicas da TV mundial?",
          isMainRecommendation: false,
        },
        {
          id: "pc3",
          category: "pergunta",
          text: "Qual a sua fala favorita de Breaking Bad além dessa?",
          isMainRecommendation: false,
        },
      ],
      hashtags: ["#categoriafilmes", "#breakingbad", "#walterwhite", "#heisenberg", "#seriesnetflix", "#melhoresmomentos", "#cenasmarcantes", "#cinema"],
      viralScore: 97,
      spoilerLevel: "baixo",
    },
    qualityChecklist: {
      workIdentified: true,
      imageFound: true,
      hookCreated: true,
      hookStrong: true,
      titleSpecific: true,
      thumbnailCreated: true,
      serialNumberAdded: true,
      imagePresent: true,
      textLegible: true,
      captionCreated: true,
      ctaCreated: true,
      commentCreated: true,
      scoreCalculated: true,
    },
    published: true,
    publishedAt: "2026-09-01T08:30:00Z",
    scheduledSlot: {
      date: "2026-09-01",
      time: "08:30",
      period: "manha",
      slotIndex: 0,
    },
    metrics: {
      views: 142300,
      likes: 19800,
      comments: 2430,
      shares: 4890,
      saves: 3750,
      retentionPct: 88.4,
      followersGained: 680,
    },
    createdAt: "2026-09-01T08:00:00Z",
    updatedAt: "2026-09-01T08:30:00Z",
  },
  {
    id: "vid-002",
    serialId: "#002",
    serialNum: 2,
    filename: "Interestelar_Docking_Scene_No_Time_For_Caution.mp4",
    fileSize: "68.7 MB",
    duration: "01:15",
    workName: "Interestelar",
    identifiedWorkConfidence: "alta",
    year: "2014",
    genre: "Ficção Científica / Suspense",
    subnicho: "Cenas Épicas & Tensão Máxima",
    status: "concluido",
    progress: 100,
    statusMessage: "Pacote completo gerado e validado",
    sceneDescription: "Cooper realiza a manobra impossível de acoplagem com a estação Endurance girando descontroladamente, enquanto a trilha sonora atinge o pico.",
    frameDataUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1200&auto=format&fit=crop",
    analysis: {
      identifiedWork: "Interestelar (2014 - Christopher Nolan)",
      confidence: "alta",
      genre: "Ficção Científica / Aventura",
      subnicho: "Cenas Épicas & Tensão Máxima",
      emotion: "Adrenalina & Suspense Extremo",
      conflictType: "Homem vs Física / Sobrevivência da Espécie",
      viralAngle: "'Não é possível' - 'Não, é necessário.' O diálogo que resume a coragem humana sob pressão implacável.",
      whyStopScroll: "A rotação visual vertiginosa e a trilha de Hans Zimmer capturam o cérebro em 0.1 segundo.",
      whyRetain: "A contagem regressiva e os giros sincronizados criam uma retenção de quase 100% até o clique de acoplagem.",
      whyComment: "O público sempre discute a física da cena e exalta a trilha sonora.",
      whyShare: "Cena frequentemente enviada como exemplo supremo de genialidade cinematográfica.",
      viralScore: 98,
      scoreBreakdown: {
        hookStrength: 99,
        curiosityGap: 97,
        visualImpact: 99,
        debatePotential: 95,
        retentionEstimate: 99,
      },
      recommendedThumbnailText: "ELE TINHA 10 SEGUNDOS",
    },
    package: {
      selectedHook: "Ele tinha apenas 10 segundos para calcular o impossível.",
      hooks: [
        { id: "h1", category: "tensão", text: "Ele tinha apenas 10 segundos para calcular o impossível.", score: 99 },
        { id: "h2", category: "curiosidade", text: "A resposta de 3 palavras que arrepiou o cinema inteiro.", score: 96 },
        { id: "h3", category: "choque", text: "A manobra mais perigosa já filmada na ficção científica.", score: 94 },
        { id: "h4", category: "mistério", text: "Por que até os cientistas da NASA elogiaram essa cena?", score: 91 },
        { id: "h5", category: "emoção", text: "O momento em que a humanidade dependia de um único homem.", score: 95 },
      ],
      selectedTitle: "A cena de Interestelar que fez todo mundo segurar a respiração",
      titles: [
        { id: "t1", category: "suspense", text: "A cena de Interestelar que fez todo mundo segurar a respiração" },
        { id: "t2", category: "curiosidade", text: "Por que a manobra de acoplagem de Interestelar é perfeita?" },
        { id: "t3", category: "emoção", text: "'Não é possível. Não, é necessário' — O clímax de Nolan" },
      ],
      selectedCaption: {
        id: "c1",
        style: "Cinematografia & Impacto",
        text: `\"Cooper, isso é impossível!\"\n\"Não... é necessário.\"\n\nA cena de acoplagem de Interestelar é, sem exagero, um dos ápices da história do cinema moderno. Christopher Nolan combinou efeitos práticos, rotação de câmera real e a trilha monumental de Hans Zimmer para criar uma experiência sensorial inigualável.\n\nVocê lembra da sensação de ver essa cena pela primeira vez? Salve e compartilhe com um fã de sci-fi! 🚀✨`,
        cta: "Quantas vezes você já reassistiu a essa cena?",
      },
      captions: [],
      selectedCta: "Quantas vezes você já reassistiu a essa cena histórica?",
      ctas: ["Quantas vezes você já reassistiu a essa cena histórica?"],
      selectedPinnedComment: {
        id: "pc1",
        category: "ranking",
        text: "🏆 QUAL A SUA NOTA DE 0 A 10 para a trilha sonora de Hans Zimmer nessa cena? (10 é pouco!)",
        isMainRecommendation: true,
      },
      pinnedComments: [],
      hashtags: ["#categoriafilmes", "#interestelar", "#interstellar", "#christophernolan", "#hanszimmer", "#scifi", "#cinema"],
      viralScore: 98,
      spoilerLevel: "baixo",
    },
    qualityChecklist: {
      workIdentified: true,
      imageFound: true,
      hookCreated: true,
      hookStrong: true,
      titleSpecific: true,
      thumbnailCreated: true,
      serialNumberAdded: true,
      imagePresent: true,
      textLegible: true,
      captionCreated: true,
      ctaCreated: true,
      commentCreated: true,
      scoreCalculated: true,
    },
    published: true,
    publishedAt: "2026-09-01T11:30:00Z",
    scheduledSlot: {
      date: "2026-09-01",
      time: "11:30",
      period: "manha",
      slotIndex: 1,
    },
    metrics: {
      views: 189400,
      likes: 27400,
      comments: 3100,
      shares: 6890,
      saves: 5400,
      retentionPct: 91.2,
      followersGained: 1120,
    },
    createdAt: "2026-09-01T08:00:00Z",
    updatedAt: "2026-09-01T11:30:00Z",
  },
  {
    id: "vid-003",
    serialId: "#003",
    serialNum: 3,
    filename: "Joker_Murray_Franklin_Show_Live_Confrontation.mp4",
    fileSize: "52.1 MB",
    duration: "01:02",
    workName: "Coringa (Joker)",
    identifiedWorkConfidence: "alta",
    year: "2019",
    genre: "Drama / Psicológico",
    subnicho: "Conflito Social & Reviravoltas",
    status: "concluido",
    progress: 100,
    statusMessage: "Pacote completo gerado e validado",
    sceneDescription: "Arthur Fleck no talk show de Murray Franklin confronta a hipocrisia da sociedade antes do desfecho trágico ao vivo.",
    frameDataUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=1200&auto=format&fit=crop",
    analysis: {
      identifiedWork: "Coringa (2019 - Todd Phillips)",
      confidence: "alta",
      genre: "Drama / Suspense Psicológico",
      subnicho: "Conflito Social & Reviravoltas",
      emotion: "Tensão Extrema & Inquietação",
      conflictType: "Marginalizado vs Sociedade Privilegiada",
      viralAngle: "A calma perturbadora de quem já não tem nada a perder diante dos holofotes.",
      whyStopScroll: "A maquiagem marcante do Coringa e a tensão palpável entre os dois atores paralisam a rolagem.",
      whyRetain: "A certeza iminente de que algo chocante vai acontecer a qualquer segundo mantém a atenção ininterrupta.",
      whyComment: "Provoca debates sociais acalorados sobre saúde mental, empatia e caos urbano.",
      whyShare: "Atuação que rendeu o Oscar a Joaquin Phoenix e gerou milhões de edits virais.",
      viralScore: 95,
      scoreBreakdown: {
        hookStrength: 97,
        curiosityGap: 95,
        visualImpact: 96,
        debatePotential: 98,
        retentionEstimate: 94,
      },
      recommendedThumbnailText: "ELE NÃO ESTAVA BRINCANDO",
    },
    package: {
      selectedHook: "O apresentador achou que era uma piada até ser tarde demais.",
      hooks: [
        { id: "h1", category: "tensão", text: "O apresentador achou que era uma piada até ser tarde demais.", score: 97 },
        { id: "h2", category: "choque", text: "A fala que fez a plateia inteira congelar no estúdio.", score: 96 },
        { id: "h3", category: "reviravolta", text: "Quando você percebe que ele foi lá com um único objetivo.", score: 95 },
      ],
      selectedTitle: "O momento em que Arthur Fleck calou a televisão ao vivo",
      titles: [
        { id: "t1", category: "choque", text: "O momento em que Arthur Fleck calou a televisão ao vivo" },
        { id: "t2", category: "debate", text: "A fala do Coringa que incomodou tanta gente em 2019" },
      ],
      selectedCaption: {
        id: "c1",
        style: "Análise Psicológica & Debate",
        text: `\"O que você ganha quando cruza um doente mental solitário com uma sociedade que o abandona e o trata como lixo?\"\n\nA tensão acumulada nesta cena de Coringa é um estudo de direção. Joaquin Phoenix e Robert De Niro criam um duelo verbal onde cada segundo que passa aperta ainda mais a corda.\n\nQual foi a sua reação quando viu essa cena no cinema? Comente abaixo! 👇🤡`,
        cta: "Qual foi a sua reação quando viu essa cena no cinema?",
      },
      captions: [],
      selectedCta: "Você acha que a atitude dele era evitável pela sociedade?",
      ctas: ["Você acha que a atitude dele era evitável pela sociedade?"],
      selectedPinnedComment: {
        id: "pc1",
        category: "debate",
        text: "💬 A culpa do desfecho foi da sociedade ou da maldade individual de Arthur? Deixe sua visão!",
        isMainRecommendation: true,
      },
      pinnedComments: [],
      hashtags: ["#categoriafilmes", "#joker", "#coringa", "#joaquinphoenix", "#cinema", "#melhorescenas"],
      viralScore: 95,
      spoilerLevel: "baixo",
    },
    qualityChecklist: {
      workIdentified: true,
      imageFound: true,
      hookCreated: true,
      hookStrong: true,
      titleSpecific: true,
      thumbnailCreated: true,
      serialNumberAdded: true,
      imagePresent: true,
      textLegible: true,
      captionCreated: true,
      ctaCreated: true,
      commentCreated: true,
      scoreCalculated: true,
    },
    published: false,
    scheduledSlot: {
      date: "2026-09-01",
      time: "14:00",
      period: "tarde",
      slotIndex: 0,
    },
    createdAt: "2026-09-01T08:00:00Z",
    updatedAt: "2026-09-01T12:00:00Z",
  },
  {
    id: "vid-004",
    serialId: "#004",
    serialNum: 4,
    filename: "Harry_Potter_Snape_Always_Memory_Scene.mp4",
    fileSize: "38.9 MB",
    duration: "00:48",
    workName: "Harry Potter e as Relíquias da Morte",
    identifiedWorkConfidence: "alta",
    year: "2011",
    genre: "Fantasia / Drama Emocional",
    subnicho: "Reviravoltas Emocionais & Nostalgia",
    status: "concluido",
    progress: 100,
    statusMessage: "Pacote completo gerado e validado",
    sceneDescription: "Harry mergulha na penseira e descobre o sacrifício de Severo Snape e a icônica revelação do Patrono 'Always'.",
    frameDataUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=1200&auto=format&fit=crop",
    analysis: {
      identifiedWork: "Harry Potter e as Relíquias da Morte: Parte 2 (2011)",
      confidence: "alta",
      genre: "Fantasia / Drama",
      subnicho: "Reviravoltas Emocionais & Nostalgia",
      emotion: "Nostalgia & Tristeza Profunda",
      conflictType: "Segredo de uma Vida Inteira / Amor Não Correspondido",
      viralAngle: "Sete filmes acreditando que ele era o vilão, para descobrir que ele foi o maior protetor.",
      whyStopScroll: "O visual do Patrono de corsa prateado e o rosto comovente de Alan Rickman despertam memória afetiva imediata.",
      whyRetain: "A revelação em camadas mantém o público absorvido até a célebre frase final.",
      whyComment: "A base de fãs sempre se manifesta em peso com homenagens a Alan Rickman.",
      whyShare: "Vídeo com taxa de compartilhamento altíssima em grupos de cultura pop.",
      viralScore: 96,
      scoreBreakdown: {
        hookStrength: 95,
        curiosityGap: 96,
        visualImpact: 94,
        debatePotential: 96,
        retentionEstimate: 98,
      },
      recommendedThumbnailText: "ELE PROTEGEU ATÉ O FIM",
    },
    package: {
      selectedHook: "7 filmes acreditando no vilão para descobrir a verdade mais dolorosa.",
      hooks: [
        { id: "h1", category: "emoção", text: "7 filmes acreditando no vilão para descobrir a verdade mais dolorosa.", score: 98 },
        { id: "h2", category: "nostalgia", text: "A palavra que fez uma geração inteira chorar no cinema.", score: 96 },
      ],
      selectedTitle: "A maior reviravolta da história do cinema de fantasia",
      titles: [{ id: "t1", category: "emoção", text: "A maior reviravolta da história de Harry Potter" }],
      selectedCaption: {
        id: "c1",
        style: "Nostalgia & Emoção",
        text: `\"Depois de todo esse tempo?\"\n\"Sempre.\"\n\nA revelação das memórias de Snape redefiniu toda a saga de Harry Potter em menos de 5 minutos de cena. Um trabalho monumental de atuação de Alan Rickman que ficará marcado para a eternidade.\n\nVocê também chorou nessa cena? Deixe um '⚡' nos comentários em homenagem!`,
        cta: "Deixe um '⚡' se você chorou nessa cena!",
      },
      captions: [],
      selectedCta: "Snape é o melhor personagem da saga inteira? Sim ou Não?",
      ctas: ["Snape é o melhor personagem da saga inteira? Sim ou Não?"],
      selectedPinnedComment: {
        id: "pc1",
        category: "debate",
        text: "⚡ Severo Snape foi um herói redimido ou suas atitudes com Harry ainda eram questionáveis? Quero ver os potterheads debatendo!",
        isMainRecommendation: true,
      },
      pinnedComments: [],
      hashtags: ["#categoriafilmes", "#harrypotter", "#snape", "#always", "#alanrickman", "#cinema"],
      viralScore: 96,
      spoilerLevel: "baixo",
    },
    qualityChecklist: {
      workIdentified: true,
      imageFound: true,
      hookCreated: true,
      hookStrong: true,
      titleSpecific: true,
      thumbnailCreated: true,
      serialNumberAdded: true,
      imagePresent: true,
      textLegible: true,
      captionCreated: true,
      ctaCreated: true,
      commentCreated: true,
      scoreCalculated: true,
    },
    published: false,
    scheduledSlot: {
      date: "2026-09-01",
      time: "17:30",
      period: "tarde",
      slotIndex: 1,
    },
    createdAt: "2026-09-01T08:00:00Z",
    updatedAt: "2026-09-01T12:30:00Z",
  },
  {
    id: "vid-005",
    serialId: "#005",
    serialNum: 5,
    filename: "Stranger_Things_Running_Up_That_Hill_Max_Scene.mp4",
    fileSize: "61.3 MB",
    duration: "01:20",
    workName: "Stranger Things",
    identifiedWorkConfidence: "alta",
    year: "2022",
    genre: "Terror / Ficção Sobrenatural",
    subnicho: "Cenas Épicas de Fuga & Tensão",
    status: "aguardando",
    progress: 0,
    statusMessage: "Pronto para análise de cena e copywriting",
    sceneDescription: "Max escapa da maldição de Vecna no Mundo Invertido correndo ao som de Kate Bush enquanto seus amigos tentam acordá-la no cemitério.",
    frameDataUrl: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?q=80&w=1200&auto=format&fit=crop",
    qualityChecklist: {
      workIdentified: true,
      imageFound: true,
      hookCreated: false,
      hookStrong: false,
      titleSpecific: false,
      thumbnailCreated: false,
      serialNumberAdded: false,
      imagePresent: true,
      textLegible: false,
      captionCreated: false,
      ctaCreated: false,
      commentCreated: false,
      scoreCalculated: false,
    },
    published: false,
    createdAt: "2026-09-01T09:00:00Z",
    updatedAt: "2026-09-01T09:00:00Z",
  },
  {
    id: "vid-006",
    serialId: "#006",
    serialNum: 6,
    filename: "Oppenheimer_Trinity_Test_Countdown_Silence.mp4",
    fileSize: "74.0 MB",
    duration: "01:32",
    workName: "Oppenheimer",
    identifiedWorkConfidence: "alta",
    year: "2023",
    genre: "Drama Histórico / Suspense",
    subnicho: "Tensão Cinematográfica & Silêncio",
    status: "aguardando",
    progress: 0,
    statusMessage: "Pronto para análise de cena e copywriting",
    sceneDescription: "A contagem regressiva para a detonação do Teste Trinity no deserto de Los Alamos, culminando no silêncio absoluto antes da onda de choque sonora.",
    frameDataUrl: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?q=80&w=1200&auto=format&fit=crop",
    qualityChecklist: {
      workIdentified: true,
      imageFound: true,
      hookCreated: false,
      hookStrong: false,
      titleSpecific: false,
      thumbnailCreated: false,
      serialNumberAdded: false,
      imagePresent: true,
      textLegible: false,
      captionCreated: false,
      ctaCreated: false,
      commentCreated: false,
      scoreCalculated: false,
    },
    published: false,
    createdAt: "2026-09-01T09:30:00Z",
    updatedAt: "2026-09-01T09:30:00Z",
  },
];
