import { ThumbnailTemplate } from "../types";

export const DEFAULT_TEMPLATES: ThumbnailTemplate[] = [
  {
    id: "template-01",
    name: "CAT FILMES — TEMPLATE 01 (Blockbuster Dourado)",
    category: "Cinematográfico",
    description: "Ideal para cenas épicas, revelações e momentos lendários com detalhes em ouro e contraste premium.",
    badgeStyle: "gold_pill",
    fontFamily: "'Bebas Neue', sans-serif",
    hookFontSize: 92,
    textColor: "#FFFFFF",
    strokeColor: "#000000",
    strokeWidth: 6,
    accentColor: "#F59E0B",
    gradientOverlay: "bottom",
    vignetteStrength: 0.65,
    brandText: "CATEGORIA FILMES",
    hookOffsetY: 68,
    titleOffsetY: 88,
    previewBg: "linear-gradient(135deg, #1e1b18 0%, #0a0a0a 100%)",
  },
  {
    id: "template-02",
    name: "CAT FILMES — TEMPLATE 02 (Suspense & Mistério Noir)",
    category: "Suspense",
    description: "Foco em tensão psicológica, choque e enigmas com detalhes carmesim e sombra pesada.",
    badgeStyle: "crimson_box",
    fontFamily: "'Montserrat', sans-serif",
    hookFontSize: 76,
    textColor: "#FFFFFF",
    strokeColor: "#450a0a",
    strokeWidth: 5,
    accentColor: "#EF4444",
    gradientOverlay: "top_bottom",
    vignetteStrength: 0.8,
    brandText: "CATEGORIA FILMES",
    hookOffsetY: 65,
    titleOffsetY: 86,
    previewBg: "linear-gradient(135deg, #2a0808 0%, #050505 100%)",
  },
  {
    id: "template-03",
    name: "CAT FILMES — TEMPLATE 03 (Tensão Máxima / Ação)",
    category: "Ação",
    description: "Tipografia agressiva com inclinação dinâmica e amarelo de alerta para reter a atenção em 0.2s.",
    badgeStyle: "amber_gradient",
    fontFamily: "'Montserrat', sans-serif",
    hookFontSize: 80,
    textColor: "#FEF08A",
    strokeColor: "#000000",
    strokeWidth: 7,
    accentColor: "#EAB308",
    gradientOverlay: "bottom",
    vignetteStrength: 0.7,
    brandText: "CATEGORIA FILMES",
    hookOffsetY: 66,
    titleOffsetY: 87,
    previewBg: "linear-gradient(135deg, #2b2306 0%, #0a0a0a 100%)",
  },
  {
    id: "template-04",
    name: "CAT FILMES — TEMPLATE 04 (Drama Emocional & Nostalgia)",
    category: "Drama",
    description: "Estética refinada clássica com serifas imponentes para cenas que tocam o coração ou chocam pela atuação.",
    badgeStyle: "minimal_tag",
    fontFamily: "'Cinzel', serif",
    hookFontSize: 72,
    textColor: "#F3F4F6",
    strokeColor: "#111827",
    strokeWidth: 5,
    accentColor: "#60A5FA",
    gradientOverlay: "radial",
    vignetteStrength: 0.6,
    brandText: "CATEGORIA FILMES",
    hookOffsetY: 64,
    titleOffsetY: 85,
    previewBg: "linear-gradient(135deg, #0f172a 0%, #020617 100%)",
  },
  {
    id: "template-05",
    name: "CAT FILMES — TEMPLATE 05 (Cult & Cyber / Quebra de Padrão)",
    category: "Ficção / Cult",
    description: "Bordas neon limpas e tipografia condensada para séries modernas e ficções científicas.",
    badgeStyle: "neon_bordered",
    fontFamily: "'Space Grotesk', sans-serif",
    hookFontSize: 78,
    textColor: "#FFFFFF",
    strokeColor: "#022c22",
    strokeWidth: 4,
    accentColor: "#10B981",
    gradientOverlay: "bottom",
    vignetteStrength: 0.75,
    brandText: "CATEGORIA FILMES",
    hookOffsetY: 67,
    titleOffsetY: 88,
    previewBg: "linear-gradient(135deg, #022c22 0%, #09090b 100%)",
  },
];
